FROM python:3.11-alpine

# Environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

# Install deps
RUN apk update
RUN apk add gettext git gcc libc-dev libffi-dev postgresql-dev musl-dev jpeg-dev zlib-dev

# Install requirements
COPY requirements.txt /app/requirements.txt
COPY requirements-dev.txt /app/requirements-dev.txt
COPY predeploy.sh /app/predeploy.sh

RUN pip install -r /app/requirements-dev.txt
