[tool.darker]
src = ['.']
isort = true
lint = ["flake8"]
line-length = 79

[tool.black]
preview = true

[tool.isort]
profile = "black"
multi_line_output = 3


[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "jararaca.settings"
python_files = ["test_*.py", "*_test.py", "tests/**/*.py"]
