# Generated by Django 2.1 on 2018-08-08 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='eventcheck',
            options={'verbose_name': 'event check', 'verbose_name_plural': 'event checks'},
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(verbose_name='end date/time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(verbose_name='start date/time'),
        ),
        migrations.AlterField(
            model_name='eventcheck',
            name='entrance_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='entrance date/time'),
        ),
        migrations.AlterField(
            model_name='eventcheck',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.api.Event',
                                    verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='eventcheck',
            name='exit_date',
            field=models.DateTimeField(null=True, verbose_name='exit date/time'),
        ),
        migrations.AlterField(
            model_name='eventcheck',
            name='member_email',
            field=models.EmailField(max_length=300, verbose_name='member email'),
        ),
        migrations.AlterField(
            model_name='eventcheck',
            name='member_name',
            field=models.CharField(max_length=300, verbose_name='member name'),
        ),
    ]
