# Generated by Django 2.1 on 2018-08-21 22:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_auto_20180821_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content_link',
            field=models.URLField(null=True, verbose_name='content link'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
