# Generated by Django 2.1.3 on 2018-11-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0009_auto_20181127_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subevent',
            old_name='event',
            new_name='event_day',
        ),
        migrations.AlterField(
            model_name='event',
            name='certificate_model',
            field=models.ImageField(blank=True, help_text='Image sized 2000x1545 ', null=True, upload_to='',
                                    verbose_name='certificate model'),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='certificate_model',
            field=models.ImageField(blank=True, help_text='Image sized 2000x1545', null=True, upload_to='',
                                    verbose_name='certificate model'),
        ),
    ]
