# Generated by Django 2.1.5 on 2019-02-01 22:00

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0012_auto_20181129_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image',
                 models.ImageField(help_text='Image sized 2000x1545', upload_to='', verbose_name='certificate image')),
                ('text', models.TextField(verbose_name='text')),
                ('font', models.FileField(help_text='TrueType font', upload_to='', verbose_name='font')),
                ('font_size', models.IntegerField(verbose_name='font size')),
                ('font_color', colorful.fields.RGBColorField(verbose_name='font color')),
                ('alignment', models.CharField(choices=[('left', 'Left')], max_length=10, verbose_name='alignment')),
                ('line_spacing', models.IntegerField(verbose_name='line spacing')),
                ('text_x', models.FloatField(help_text='Percentage from model width', verbose_name='text X position')),
                ('text_y', models.FloatField(help_text='Percentage from model height', verbose_name='text Y position')),
                ('text_width', models.FloatField(verbose_name='text width')),
            ],
            options={
                'verbose_name': 'certificate model',
                'verbose_name_plural': 'certificate models',
            },
        ),
    ]
