# Generated by Django 2.1.5 on 2019-02-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0013_certificatemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='certificate_model',
        ),
        migrations.RemoveField(
            model_name='subevent',
            name='certificate_model',
        ),
        migrations.AlterField(
            model_name='certificatemodel',
            name='alignment',
            field=models.CharField(
                choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center'), ('justify', 'Justify')],
                max_length=10, verbose_name='alignment'),
        ),
        migrations.AlterField(
            model_name='certificatemodel',
            name='font',
            field=models.FileField(help_text='TrueType font file', upload_to='', verbose_name='font'),
        ),
        migrations.AlterField(
            model_name='certificatemodel',
            name='text_width',
            field=models.FloatField(help_text='Percentage from model width', verbose_name='text width'),
        ),
    ]
