# Generated by Django 2.1.5 on 2019-02-01 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0014_auto_20190201_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='certificate_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='apps.api.CertificateModel', verbose_name='certificate model'),
        ),
        migrations.AddField(
            model_name='subevent',
            name='certificate_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='apps.api.CertificateModel', verbose_name='certificate model'),
        ),
    ]
