# Generated by Django 2.1.7 on 2019-03-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_event_certificate_minimum_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='certificate_minimum_time',
            field=models.IntegerField(default=75, help_text='Percentage from total time', verbose_name='minimum length of stay for certificate'),
        ),
    ]
