# Generated by Django 2.1.7 on 2019-12-05 17:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20191205_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('share_data_with_partners', models.BooleanField(default=False, verbose_name='share data with partners')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('auth', models.BooleanField(default=False, verbose_name='auth')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'organizer',
                'verbose_name_plural': 'organizers',
            },
        ),
    ]
