# Generated by Django 2.1.7 on 2019-12-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='certificate_hours_org',
            field=models.IntegerField(default=10, verbose_name='organization certificate hours'),
        ),
    ]
