# Generated by Django 2.1.7 on 2019-12-06 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20191205_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='certificate_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_certificate_model', to='api.CertificateModel', verbose_name='certificate model'),
        ),
        migrations.AlterField(
            model_name='event',
            name='certificate_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='org_certificate_model', to='api.CertificateModel', verbose_name='organization certificate model'),
        ),
    ]
