# Generated by Django 2.1.7 on 2019-12-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20191205_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='auth_org',
            field=models.BooleanField(default=False, verbose_name='auth'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='organization',
            field=models.BooleanField(default=False, verbose_name='participate in the organization'),
        ),
    ]
