# Generated by Django 2.1.7 on 2019-12-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20191206_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='auth_org',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='organization',
        ),
        migrations.AddField(
            model_name='attendee',
            name='permission_to_be_an_organizer',
            field=models.BooleanField(default=False, verbose_name='permission to be an organizer'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='want_to_be_an_organizer',
            field=models.BooleanField(default=False, verbose_name='want to be an organizer'),
        ),
    ]
