# Generated by Django 2.1 on 2018-08-22 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180821_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'verbose_name': 'attendee', 'verbose_name_plural': 'attendees'},
        ),
        migrations.AddField(
            model_name='attendee',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
    ]
