# Generated by Django 2.1 on 2018-08-22 01:31

from django.db import migrations, models
from uuid import uuid4

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=uuid4, unique=True),
            preserve_default=False,
        ),
    ]
