# Generated by Django 2.1 on 2018-08-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_event_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventschedule',
            options={'ordering': ['start'], 'verbose_name': 'event schedule', 'verbose_name_plural': 'event schedules'},
        ),
        migrations.AlterField(
            model_name='event',
            name='content_link',
            field=models.URLField(blank=True, null=True, verbose_name='content link'),
        ),
        migrations.AlterUniqueTogether(
            name='eventday',
            unique_together={('event', 'date')},
        ),
    ]
