# Generated by Django 2.1.3 on 2018-11-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20181127_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='certificate_hours',
            field=models.IntegerField(default=4, verbose_name='certificate hours'),
        ),
        migrations.AddField(
            model_name='subevent',
            name='certificate_hours',
            field=models.IntegerField(default=4, verbose_name='certificate hours'),
        ),
        migrations.AlterField(
            model_name='event',
            name='certificate_model',
            field=models.ImageField(blank=True, help_text='Image sized 2000x1545', null=True, upload_to='', verbose_name='certificate model'),
        ),
    ]
