# Generated by Django 2.1.7 on 2019-03-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190201_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='certificate_minimum_time',
            field=models.IntegerField(default=75, help_text='Percentage from total time', verbose_name='certificate minimum time'),
        ),
    ]
