name: Roda o lint

on: [push, pull_request]

jobs:
  lint:
    name: Roda o darker para verificar apenas o código que foi mudado nessas branch

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7.17"

      - uses: akaihola/darker@1.7.3
        with:
          options: "--check --diff --isort --color"
          src: "."
          version: "~=1.7.3"
          lint: "flake8==5.0.4"
