name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Pylint
      run: |
        # list out files that are in directory and working tree
        # grep -v will exclude the files being considered for pylint
        # grep -E will matches files having .py extension
        # This command will help to pass required python files to pylint along with pylint_djanog plugin
        # Pylint with -E option will display only if there is any error
        git ls-files | grep -v 'migrations' | grep -v 'settings.py' | grep -v 'manage.py' | grep -E '.py$' |
          xargs pylint -E --load-plugins=pylint_django
    #- name: Test with pytest
    #  run: |
    #    pip install pytest
    #    pytest
